/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import java.io.IOException;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import org.junit.jupiter.api.Test;

/**
 * Test the database connection to the testing environment.
 */
class TestDevEnv {
    public static final String URL = "jdbc:postgresql://www.djpiper28.co.uk:6445/teamdev",
                               USERNAME = "dev",
                               PASSWORD = "REDACTED";

    @Test void testDatabaseConnection() throws SQLException, IOException {
        Connection conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
        conn.close();
    }
}
